// lib/site-config.ts
// SINGLE SOURCE OF TRUTH FOR MINI HIGHLAND COWS (MHC PTY LTD)

export interface AnimalProduct {
  id: string;
  slug: string;
  name: string;
  price: number; // in AUD, includes GST
  category: 'breeding-foundation' | 'paddock-companions' | 'care-equipment';
  subcategory:
    | 'heifers'
    | 'cows-in-calf-pairs'
    | 'steers'
    | 'weaners-calves'
    | 'grooming-handling'
    | 'paddock-shelter'
    | 'feed-nutrition';
  categoryLabel: string;
  subcategoryLabel: string;
  badge?: string;
  featured?: boolean;
  itemType?: 'livestock' | 'equipment' | 'feed';

  // Livestock & Biological Characteristics
  sex?: 'Heifer' | 'Steer' | 'Cow in Calf' | 'Breeding Pair' | 'Heifer Calf' | 'Steer Calf' | 'Care Equipment' | 'Feed & Nutrition';
  sizeClass?: 'Micro' | 'Miniature' | 'Universal Equipment' | 'Feed Supply';
  heightInches?: number; // mature height in inches
  color?: string;
  chondroStatus?: string;
  hornStatus?: string;
  registry?: string;
  dobOrAge?: string;
  temperament?: string;
  vaccination?: string;

  // Equipment / Feed specific specifications
  dimensionsOrPack?: string;
  warrantyOrShelfLife?: string;
  compatibility?: string;

  shortDescription: string;
  fullDescription: string;
  image: string;
  imageSourcingPrompt: string; // Precise visual description to help source or match photos
}

export const SITE = {
  name: 'Mini Highland Cows (MHC PTY LTD)',
  tagline: 'Mini Highland Cows for Sale',
  description: "Australia's premier ethical breeder of registered miniature and micro Scottish Highland cattle based in Roma, QLD.",
  companyName: 'MHC PTY LTD',
  acn: '158 390 973',
  abn: '23 158 390 973',
  abnLookupUrl: 'https://abr.business.gov.au/ABN/View?id=23158390973',
  regDate: '16/05/2012',
  locality: 'ROMA QLD 4455',
  country: 'Australia',
  currency: 'AUD',
  locale: 'en-AU',
  primaryColor: '#B08D57',
  secondaryColor: '#232320',
  freeShippingThreshold: 2000,
  cryptoDiscountPct: 10,
  domain: 'DOMAIN.com',
  picNlisText: 'All livestock sales require valid buyer PIC (Property Identification Code) and include NLIS electronic RFID transfer as mandated by Biosecurity Australia & MLA.',
};

export const CONTACT = {
  email: 'hello@thehighlandfold.com.au',
  phone: '+61 400 000 000',
  whatsapp: '+61400000000',
  location: 'Roma, Queensland 4455, Australia',
  operatingHours: 'Mon - Sat: 8:00am - 6:00pm AEST',
};

export const FORMS = {
  provider: 'web3forms',
  web3formsKey: 'PENDING',
};

export const CATEGORIES = [
  {
    id: 'breeding-foundation',
    name: 'Breeding Foundation',
    description: 'High-end pedigree genetics, registered micro heifers, and proven cows in calf.',
    subcategories: [
      { id: 'heifers', name: 'Registered Heifers (Micro & Mini)' },
      { id: 'cows-in-calf-pairs', name: 'Cows in Calf & Foundation Pairs' },
    ],
  },
  {
    id: 'paddock-companions',
    name: 'Paddock Companions',
    description: 'Docile halter-trained desexed steers and sweet hand-reared bottle calves for lifestyle acreage.',
    subcategories: [
      { id: 'steers', name: 'Halter-Trained Steers (Pets)' },
      { id: 'weaners-calves', name: 'Weaned Calves & Bottle Babies' },
    ],
  },
  {
    id: 'care-equipment',
    name: 'Care Equipment & Feed',
    description: 'Elite grooming blowers, leather halters, slow-feed cradles, automatic troughs, and stud nutrition.',
    subcategories: [
      { id: 'grooming-handling', name: 'Grooming Blowers & Halters' },
      { id: 'paddock-shelter', name: 'Troughs, Scratchers & Hay Cradles' },
      { id: 'feed-nutrition', name: 'Lucerne Hay & Stud Nutrition' },
    ],
  },
];

export interface BrandItem {
  id: string;
  name: string;
  shortName: string;
  slug: string;
  description: string;
  badge: string;
  registryFilter: string;
}

export const BRANDS: BrandItem[] = [
  {
    id: 'ahcs-registered',
    name: 'AHCS Registered Bloodline',
    shortName: 'AHCS Registered',
    slug: 'ahcs-registered',
    description: 'Pedigree stock registered with the Australian Highland Cattle Society.',
    badge: 'AHCS Pedigree',
    registryFilter: 'AHCS Registered',
  },
  {
    id: 'imcbr-registered',
    name: 'IMCBR Miniature Bloodline',
    shortName: 'IMCBR Registered',
    slug: 'imcbr-registered',
    description: 'International Miniature Cattle Breeder Registry certified small-frame genetics.',
    badge: 'IMCBR Verified',
    registryFilter: 'IMCBR Registered',
  },
  {
    id: 'mhc-signature',
    name: 'MHC Roma Signature Foundation',
    shortName: 'MHC Signature',
    slug: 'mhc-signature',
    description: 'Direct foundation genetics bred at our closed-gate Roma QLD stud.',
    badge: 'MHC Pure Stud',
    registryFilter: 'MHC',
  },
  {
    id: 'loch-lomond-heritage',
    name: 'Loch Lomond Scottish Heritage',
    shortName: 'Loch Lomond',
    slug: 'loch-lomond-heritage',
    description: 'Direct imported Scottish semen lines with high genetic docility and thick double-coats.',
    badge: 'Heritage Genetics',
    registryFilter: 'Scottish',
  },
  {
    id: 'highpark-pointed',
    name: 'Highpark Pointed Genetics',
    shortName: 'Highpark Pointed',
    slug: 'highpark-pointed',
    description: 'Rare white coats with distinct black or silver tips and points.',
    badge: 'Pointed Coat',
    registryFilter: 'Highpark',
  },
  {
    id: 'pet-quality',
    name: 'Lifestyle Paddock Companions',
    shortName: 'Pet Lineage',
    slug: 'pet-quality',
    description: 'Calm, halter-trained steers and heifers for family lifestyle hobby farms.',
    badge: 'Gentle Pet',
    registryFilter: 'Pet Quality',
  },
  {
    id: 'mhc-gear',
    name: 'MHC Master Equipment & Feed',
    shortName: 'MHC Master Gear',
    slug: 'mhc-gear',
    description: 'Elite paddock infrastructure, custom leather tack, and veterinary-formulated nutrition.',
    badge: 'Stud Approved',
    registryFilter: 'Equipment',
  },
];

// EXACT CATALOG: 23 COWS + 10 CARE EQUIPMENT & PREMIUM FEED (33 PRODUCTS TOTAL)
export const PRODUCTS: AnimalProduct[] = [
  // =========================================================================
  // SECTION 1: 23 CURATED MINIATURE & MICRO SCOTTISH HIGHLAND COWS
  // =========================================================================

  // --- 1A. REGISTERED HEIFERS (12 Cows) ---
  {
    id: 'mhc-01',
    slug: 'isla-silver-micro-heifer',
    name: 'Aila',
    price: 12800,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Rare Silver',
    featured: true,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Micro',
    heightInches: 34,
    color: 'Silver',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'AHCS Registered',
    dobOrAge: '14 Months',
    temperament: 'Extremely sweet, loves being brushed, leads on halter',
    vaccination: '7-in-1, Pestivirus tested negative, multimin 4+ selenium drenched',
    shortDescription: 'Ultra-rare platinum silver micro heifer with dense double coat. Non-chondro genetics.',
    fullDescription: 'Aila is an extraordinary showcase of miniature Scottish Highland genetics. Standing just 34 inches at 14 months, she boasts a true silver frost coat with thick ear fringes and impeccable square conformation. DNA tested negative for chondrodysplasia.',
    image: '/images/isla-silver-micro-heifer.webp',
    imageSourcingPrompt: 'Silver grey miniature highland cow heifer standing in Australian paddock pasture, long woolly silver coat, gentle brown eyes, small curved horns, natural daylight 4:3 ratio',
  },
  {
    id: 'mhc-02',
    slug: 'thistle-snow-white-micro-heifer',
    name: 'Thistle',
    price: 14200,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Ultra Rare White',
    featured: true,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Micro',
    heightInches: 32,
    color: 'Snow White',
    chondroStatus: 'Chondro+ (Carrier Dwarfism Gene)',
    hornStatus: 'Developing Horn Buds',
    registry: 'IMCBR Registered',
    dobOrAge: '11 Months',
    temperament: 'Pocket-sized lap pet personality, follows handlers everywhere',
    vaccination: '7-in-1, BVDV clear, drenching complete',
    shortDescription: 'Pure snow-white micro heifer. Extremely compact 32-inch hip height.',
    fullDescription: 'Thistle is one of our rarest micro heifers. Her coat is brilliant pure snow white without markings. Exceptionally short cannon bones, fluffy dossier forehead wool, and playful temperament.',
    image: '/images/thistle-snow-white-micro-heifer.webp',
    imageSourcingPrompt: 'Pure white fluffy miniature highland cow heifer grazing in lush green grass paddock, bright eyes, woolly white coat, natural sunlight 4:3 ratio',
  },
  {
    id: 'mhc-03',
    slug: 'bramble-jet-black-micro-heifer',
    name: 'Bramble',
    price: 9800,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Midnight Black',
    featured: true,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Micro',
    heightInches: 33,
    color: 'Jet Black',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Polled (Naturally Hornless)',
    registry: 'AHCS Registered',
    dobOrAge: '16 Months',
    temperament: 'Quiet and dignified, very easy to handle in yards and crush',
    vaccination: '7-in-1, Pestivirus negative, vitamin A, D, E booster',
    shortDescription: 'True jet black micro heifer. Naturally polled (hornless) foundation bloodline.',
    fullDescription: 'Bramble represents the highest tier of polled Scottish genetics. Midnight black from nose to tail with no scurs or horns. Perfect for families desiring safety around young children without dehorning.',
    image: '/images/bramble-jet-black-micro-heifer.webp',
    imageSourcingPrompt: 'Jet black miniature highland cow heifer in open pasture, thick black wavy coat, calm expression, naturally hornless polled head, professional pastoral photography 4:3',
  },
  {
    id: 'mhc-04',
    slug: 'saffron-honey-yellow-miniature-heifer',
    name: 'Saffron',
    price: 8800,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Golden Yellow',
    featured: false,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Miniature',
    heightInches: 39,
    color: 'Honey Yellow',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'AHCS Registered',
    dobOrAge: '18 Months',
    temperament: 'Loves molasses treats, walks politely on lead',
    vaccination: '7-in-1, BVDV clear, drench up to date',
    shortDescription: 'Warm golden yellow miniature heifer with thick amber fleece and classic Scottish horns.',
    fullDescription: 'Saffron boasts rich honey-yellow coloration with golden blonde highlights across her dorsal ridge. Exceptional bone density and depth of rib. Ready to join a breeding program this spring.',
    image: '/images/saffron-honey-yellow-miniature-heifer.webp',
    imageSourcingPrompt: 'Golden yellow miniature Scottish highland cow heifer standing on grassy hill under morning sun, long golden fur, classical curved horns 4:3 ratio',
  },
  {
    id: 'mhc-05',
    slug: 'heather-smoky-dun-miniature-heifer',
    name: 'Heather',
    price: 8900,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Heritage Dun',
    featured: false,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Miniature',
    heightInches: 38,
    color: 'Smoky Dun',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'AHCS Registered',
    dobOrAge: '15 Months',
    temperament: 'Gentle nature, comes to fence when called by name',
    vaccination: '7-in-1, Pestivirus tested negative, drenched',
    shortDescription: 'Charming smoky dun miniature heifer. Traditional Scottish heritage coloration.',
    fullDescription: 'Heather showcases the iconic slate-grey smoky dun coat prized in Scottish herd books. Dense woolly undercoat suited to all Australian climates from Southern Highlands frost to Roma heat.',
    image: '/images/heather-smoky-dun-miniature-heifer.webp',
    imageSourcingPrompt: 'Smoky dun grey miniature highland cow with thick wool coat grazing in green meadow pasture, gentle eyes, 4:3 ratio',
  },
  {
    id: 'mhc-06',
    slug: 'bonnie-platinum-silver-miniature-heifer',
    name: 'Bonnie',
    price: 12200,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Platinum Silver',
    featured: true,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Miniature',
    heightInches: 37,
    color: 'Silver',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'AHCS Registered',
    dobOrAge: '17 Months',
    temperament: 'Very calm, halter trained, loves chin scratches',
    vaccination: '7-in-1, Pestivirus negative, Multimin drenched',
    shortDescription: 'Sensational platinum silver heifer with silver frost mane and black hooves.',
    fullDescription: 'Bonnie is an absolute showstopper. Her coat is an ethereal silvery white with dark charcoal skin pigmentation protecting against sunburn. Exceptional pedigree tracking back to Balgownie imported genetics.',
    image: '/images/bonnie-platinum-silver-miniature-heifer.webp',
    imageSourcingPrompt: 'Platinum silver miniature highland cow standing proudly in paddock, thick silver fleece, black muzzle, gentle expression, natural lighting 4:3 ratio',
  },
  {
    id: 'mhc-07',
    slug: 'ember-highpark-pointed-miniature-heifer',
    name: 'Ember',
    price: 9200,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Highpark Pointed',
    featured: false,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Miniature',
    heightInches: 38,
    color: 'Highpark Pointed',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Developing Horn Buds',
    registry: 'IMCBR Registered',
    dobOrAge: '13 Months',
    temperament: 'Curious, playful, loves treats and paddock brushing',
    vaccination: '7-in-1, BVDV clear, drench complete',
    shortDescription: 'White fleece with distinct black ear tips, black nose, and black hooves.',
    fullDescription: 'Ember features the sought-after Highpark pointed pattern. Her coat is brilliant ivory white offset by jet-black ear tips, eyeliner pigmentation, and dark hooves. High genetic vigor and great maternal instincts.',
    image: '/images/ember-highpark-pointed-miniature-heifer.webp',
    imageSourcingPrompt: 'White miniature highland cow heifer with black ears and black nose points Highpark markings in green Australian pasture 4:3 ratio',
  },
  {
    id: 'mhc-08',
    slug: 'wren-ruby-red-miniature-heifer',
    name: 'Wren',
    price: 8200,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Ruby Red',
    featured: false,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Miniature',
    heightInches: 39,
    color: 'Scottish Red',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'AHCS Registered',
    dobOrAge: '19 Months',
    temperament: 'Quiet, dependable herd member, easily handled by beginners',
    vaccination: '7-in-1, Pestivirus negative, drenched',
    shortDescription: 'Vibrant ruby red miniature heifer with long cascading forelock.',
    fullDescription: 'Wren embodies the timeless Scottish Highland aesthetic with a deep, rich mahogany red coat. Thickly fleshed over the loin with strong legs and balanced feet. Ready for service.',
    image: '/images/wren-ruby-red-miniature-heifer.webp',
    imageSourcingPrompt: 'Rich red miniature Scottish highland heifer standing in paddock pasture, reddish brown long coat, symmetrical horns, daylight 4:3',
  },
  {
    id: 'mhc-10',
    slug: 'clover-tiger-brindle-miniature-heifer',
    name: 'Clover',
    price: 9500,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Tiger Brindle',
    featured: false,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Miniature',
    heightInches: 38,
    color: 'Tiger Brindle',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'AHCS Registered',
    dobOrAge: '16 Months',
    temperament: 'Affectionate, inquisitive, comes for hand-fed Lucerne',
    vaccination: '7-in-1, BVDV clear, Multimin 4 drenched',
    shortDescription: 'Striking tiger-striped brindle coat with golden undertones.',
    fullDescription: 'Clover exhibits extraordinary brindle patterning with dark espresso tiger stripes undulating across a golden amber ground coat. Perfect confirmation and registration pedigree.',
    image: '/images/clover-tiger-brindle-miniature-heifer.webp',
    imageSourcingPrompt: 'Tiger brindle miniature highland cow heifer with dark brown and golden stripes in sunny paddock, long hair, Scottish horns 4:3',
  },
  {
    id: 'mhc-11',
    slug: 'gemma-champagne-yellow-micro-heifer',
    name: 'Gemma',
    price: 10800,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Micro Yellow',
    featured: false,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Micro',
    heightInches: 33,
    color: 'Honey Yellow',
    chondroStatus: 'Chondro+ (Carrier Dwarfism Gene)',
    hornStatus: 'Developing Horn Buds',
    registry: 'IMCBR Registered',
    dobOrAge: '12 Months',
    temperament: 'Docile, gentle, great with small children',
    vaccination: '7-in-1, Pestivirus negative, drenched',
    shortDescription: 'Petite 33-inch champagne yellow micro heifer. Soft silky coat.',
    fullDescription: 'Gemma has a light champagne yellow fleece that shines like spun silk. Compact, stocky, and charming, she has been raised with daily handling on our Roma stud.',
    image: '/images/gemma-champagne-yellow-micro-heifer.webp',
    imageSourcingPrompt: 'Champagne yellow micro highland heifer calf in lush grass, petite size, adorable face, long fluffy coat 4:3',
  },
  {
    id: 'mhc-15',
    slug: 'blanche-chalk-white-micro-heifer',
    name: 'Blanche',
    price: 13900,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Chalk White',
    featured: false,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Micro',
    heightInches: 32,
    color: 'Snow White',
    chondroStatus: 'Chondro+ (Carrier Dwarfism Gene)',
    hornStatus: 'Developing Horn Buds',
    registry: 'IMCBR Registered',
    dobOrAge: '10 Months',
    temperament: 'Curious, confident, follows handlers around yards',
    vaccination: '7-in-1, Pestivirus negative, Multimin clear',
    shortDescription: 'Petite chalk-white micro heifer. Extremely thick double coat.',
    fullDescription: 'Blanche is an exquisite micro specimen. Thick fleece protects against both wind and summer heat. Strong square hip conformation and friendly personality.',
    image: '/images/blanche-chalk-white-micro-heifer.webp',
    imageSourcingPrompt: 'Chalk white micro miniature highland cow heifer in paddock, thick white curls, sweet eyes, small frame 4:3',
  },
  {
    id: 'mhc-21',
    slug: 'kirsty-silver-brindle-micro-heifer',
    name: 'Kirsty',
    price: 13200,
    category: 'breeding-foundation',
    subcategory: 'heifers',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Registered Heifers',
    badge: 'Silver Brindle',
    featured: false,
    itemType: 'livestock',
    sex: 'Heifer',
    sizeClass: 'Micro',
    heightInches: 33,
    color: 'Silver',
    chondroStatus: 'Chondro+ (Carrier Dwarfism Gene)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'AHCS Registered',
    dobOrAge: '14 Months',
    temperament: 'Gentle, calm, loves coat brushing and ear rubs',
    vaccination: '7-in-1, Pestivirus negative, drenched',
    shortDescription: 'Ultra-rare silver-brindle combination in a 33-inch micro package.',
    fullDescription: 'Kirsty combines the best of both worlds: rare silver ground color overlaid with subtle charcoal brindle striping. True micro height with excellent leg correctness.',
    image: '/images/kirsty-silver-brindle-micro-heifer.webp',
    imageSourcingPrompt: 'Silver brindle micro highland heifer cow standing in green pasture, rare grey and charcoal coat, natural daylight 4:3',
  },

  // --- 1B. COWS IN CALF & FOUNDATION PAIRS (4 Cows/Units) ---
  {
    id: 'mhc-29',
    slug: 'rory-and-fern-silver-foundation-breeding-pair',
    name: 'Rory & Fern',
    price: 14500,
    category: 'breeding-foundation',
    subcategory: 'cows-in-calf-pairs',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Cows in Calf & Pairs',
    badge: 'Stud Starter Pair',
    featured: true,
    itemType: 'livestock',
    sex: 'Breeding Pair',
    sizeClass: 'Micro',
    heightInches: 36,
    color: 'Silver',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'AHCS Registered',
    dobOrAge: '2.5 Years (Pair)',
    temperament: 'Bonded pair, extremely quiet and respectful in yards',
    vaccination: 'Both 7-in-1, BVDV clear, Vibrio vaccinated',
    shortDescription: 'Matched silver micro heifer and unrelated registered bull. Complete stud starter pack.',
    fullDescription: 'An unmatched opportunity to acquire a genetically matched, unrelated foundation breeding pair. Both animals carry verifiable AHCS pedigree certificates and test clean across all biosecurity markers.',
    image: '/images/rory-and-fern-silver-foundation-breeding-pair.webp',
    imageSourcingPrompt: 'Pair of silver miniature highland cows standing together in sunny pasture paddock, bull and heifer pair, majestic Scottish horns 4:3',
  },
  {
    id: 'mhc-30',
    slug: 'maisie-scottish-red-proven-cow-in-calf',
    name: 'Maisie',
    price: 11400,
    category: 'breeding-foundation',
    subcategory: 'cows-in-calf-pairs',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Cows in Calf & Pairs',
    badge: 'Vet Confirmed in Calf',
    featured: false,
    itemType: 'livestock',
    sex: 'Cow in Calf',
    sizeClass: 'Miniature',
    heightInches: 39,
    color: 'Scottish Red',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'AHCS Registered',
    dobOrAge: '3.5 Years',
    temperament: 'Exceptional maternal instincts, calm around people and dogs',
    vaccination: '7-in-1, Pestivirus negative, drenched',
    shortDescription: 'Proven red foundation cow. Vet ultrasound confirmed in calf to Champion Silver Bull.',
    fullDescription: 'Maisie has calved once before unassisted with plentiful rich milk. Ultrasound confirmed 4 months in calf to our champion 34-inch silver micro bull Strathbogie Glen. Calving due in 5 months.',
    image: '/images/maisie-scottish-red-proven-cow-in-calf.webp',
    imageSourcingPrompt: 'Mature red miniature Scottish highland cow standing in paddock, thick mahogany coat, wide graceful horns, sunny afternoon 4:3',
  },
  {
    id: 'mhc-32',
    slug: 'greta-smoky-dun-cow-in-calf',
    name: 'Greta',
    price: 12600,
    category: 'breeding-foundation',
    subcategory: 'cows-in-calf-pairs',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Cows in Calf & Pairs',
    badge: 'Confirmed in Calf',
    featured: false,
    itemType: 'livestock',
    sex: 'Cow in Calf',
    sizeClass: 'Miniature',
    heightInches: 38,
    color: 'Smoky Dun',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'AHCS Registered',
    dobOrAge: '3 Years',
    temperament: 'Sweet personality, loves scratches under throat and ears',
    vaccination: '7-in-1, Pestivirus negative, drenched',
    shortDescription: 'Silky smoky dun cow. Ultrasound confirmed in calf to Balgownie Finlay.',
    fullDescription: 'Greta carries prestigious Scottish imported genetics. Standing 38 inches with a wide pelvis and great udder attachment. Confirmed pregnant to Balgownie Finlay (imported genetics).',
    image: '/images/greta-smoky-dun-cow-in-calf.webp',
    imageSourcingPrompt: 'Smoky dun pregnant miniature highland cow in paddock grass, calm demeanor, thick woolly coat, natural lighting 4:3',
  },
  {
    id: 'mhc-33',
    slug: 'lachlan-and-morven-snow-white-premier-stud-pair',
    name: 'Lachlan & Morven',
    price: 15000,
    category: 'breeding-foundation',
    subcategory: 'cows-in-calf-pairs',
    categoryLabel: 'Breeding Foundation',
    subcategoryLabel: 'Cows in Calf & Pairs',
    badge: 'Premier White Pair',
    featured: false,
    itemType: 'livestock',
    sex: 'Breeding Pair',
    sizeClass: 'Micro',
    heightInches: 35,
    color: 'Snow White',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'IMCBR Registered',
    dobOrAge: '2 Years (Pair)',
    temperament: 'Very bonded, calm, accustomed to paddock visitors and brush',
    vaccination: 'Both 7-in-1, BVDV clear, vaccinated and drenched',
    shortDescription: 'Matched snow-white micro pair. Unrelated genetics for high-value breeding.',
    fullDescription: 'Lachlan (bull) and Morven (heifer) represent our finest white miniature lineage. Both possess brilliant white fleece, dark pigment points, and gentle temperaments. Complete paperwork ready for transfer.',
    image: '/images/lachlan-and-morven-snow-white-premier-stud-pair.webp',
    imageSourcingPrompt: 'Two pure white miniature highland cows together in green grass paddock pasture, peaceful Australian farm setting 4:3',
  },

  // --- 1C. HALTER-TRAINED PET STEERS (5 Cows) ---
  {
    id: 'mhc-45',
    slug: 'angus-tiger-brindle-micro-pet-steer',
    name: 'Angus',
    price: 6500,
    category: 'paddock-companions',
    subcategory: 'steers',
    categoryLabel: 'Paddock Companions',
    subcategoryLabel: 'Halter-Trained Steers',
    badge: 'Family Favorite',
    featured: true,
    itemType: 'livestock',
    sex: 'Steer',
    sizeClass: 'Micro',
    heightInches: 34,
    color: 'Tiger Brindle',
    chondroStatus: 'Chondro+ (Carrier Dwarfism Gene)',
    hornStatus: 'Polled (Naturally Hornless)',
    registry: 'Pet Quality (Commercial Lineage)',
    dobOrAge: '14 Months',
    temperament: 'Golden retriever personality. Comes running for bread or apple treats',
    vaccination: '7-in-1, BVDV clear, Multimin drenched',
    shortDescription: 'Halter-broken brindle micro steer. Docile lap-pet demeanor, naturally polled.',
    fullDescription: 'Angus is the ultimate paddock pet. Desexed, vaccinated, and hand-tamed since birth. He loves children, stands quietly for grooming, and will follow you anywhere on a simple lead rope.',
    image: '/images/angus-tiger-brindle-micro-pet-steer.webp',
    imageSourcingPrompt: 'Tiger brindle miniature highland pet steer standing near timber fence, friendly eyes, fluffy face wool, paddock setting 4:3',
  },
  {
    id: 'mhc-46',
    slug: 'fergus-jet-black-miniature-pet-steer',
    name: 'Fergus',
    price: 4500,
    category: 'paddock-companions',
    subcategory: 'steers',
    categoryLabel: 'Paddock Companions',
    subcategoryLabel: 'Halter-Trained Steers',
    badge: 'Gentle Giant Pet',
    featured: false,
    itemType: 'livestock',
    sex: 'Steer',
    sizeClass: 'Miniature',
    heightInches: 38,
    color: 'Jet Black',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Dehorned',
    registry: 'Pet Quality (Commercial Lineage)',
    dobOrAge: '16 Months',
    temperament: 'Quiet, calm, respectful around fences and children',
    vaccination: '7-in-1, Pestivirus negative, drenched',
    shortDescription: 'Dehorned jet black steer. Fluffy coat and calm, docile temperament.',
    fullDescription: 'Fergus is an ideal acreage lawn mower. Naturally placid, professionally dehorned as a calf with smooth rounded skull, and completely desexed. Exceptional companion for horses or sheep.',
    image: '/images/fergus-jet-black-miniature-pet-steer.webp',
    imageSourcingPrompt: 'Fluffy jet black miniature highland steer in green pasture, hornless rounded head, gentle demeanor 4:3',
  },
  {
    id: 'mhc-47',
    slug: 'archie-snow-white-micro-pet-steer',
    name: 'Archie',
    price: 6800,
    category: 'paddock-companions',
    subcategory: 'steers',
    categoryLabel: 'Paddock Companions',
    subcategoryLabel: 'Halter-Trained Steers',
    badge: 'Teddy Bear Pet',
    featured: true,
    itemType: 'livestock',
    sex: 'Steer',
    sizeClass: 'Micro',
    heightInches: 33,
    color: 'Snow White',
    chondroStatus: 'Chondro+ (Carrier Dwarfism Gene)',
    hornStatus: 'Developing Horn Buds',
    registry: 'Pet Quality (Commercial Lineage)',
    dobOrAge: '12 Months',
    temperament: 'Like a giant living teddy bear. Loves chin rubs and hugs',
    vaccination: '7-in-1, Pestivirus negative, Multimin clear',
    shortDescription: 'Fluffy snow-white micro steer. 33 inches tall with teddy bear appeal.',
    fullDescription: 'Archie steals every visitor\'s heart. Fluffy white fleece that stands out like a cloud, short legs, and an unshakeable love for human company. Halter-broken and easy to lead.',
    image: '/images/archie-snow-white-micro-pet-steer.webp',
    imageSourcingPrompt: 'Pure white fluffy miniature highland pet steer in pasture, woolly bangs over eyes, friendly teddy bear look 4:3',
  },
  {
    id: 'mhc-50',
    slug: 'clyde-classic-scottish-red-miniature-steer',
    name: 'Clyde',
    price: 4200,
    category: 'paddock-companions',
    subcategory: 'steers',
    categoryLabel: 'Paddock Companions',
    subcategoryLabel: 'Halter-Trained Steers',
    badge: 'Affordable Pet',
    featured: false,
    itemType: 'livestock',
    sex: 'Steer',
    sizeClass: 'Miniature',
    heightInches: 39,
    color: 'Scottish Red',
    chondroStatus: 'Tested Non-Carrier (Negative)',
    hornStatus: 'Symmetrical Scottish Horns',
    registry: 'Pet Quality (Commercial Lineage)',
    dobOrAge: '18 Months',
    temperament: 'Solid, dependable, loves being brushed with stiff comb',
    vaccination: '7-in-1, Pestivirus negative, drenched',
    shortDescription: 'Traditional red miniature steer with grand Scottish horns and sweet demeanor.',
    fullDescription: 'Clyde is the classic paddock picture: rich red coat, dignified horns, and a gentle grazing demeanor. Excellent lawn keeper for 1-5 acre properties.',
    image: '/images/clyde-classic-scottish-red-miniature-steer.webp',
    imageSourcingPrompt: 'Classic Scottish red miniature highland steer grazing peaceful green pasture, iconic horns, daylight 4:3',
  },
  {
    id: 'mhc-53',
    slug: 'finley-platinum-silver-micro-steer',
    name: 'Finley',
    price: 6400,
    category: 'paddock-companions',
    subcategory: 'steers',
    categoryLabel: 'Paddock Companions',
    subcategoryLabel: 'Halter-Trained Steers',
    badge: 'Rare Silver Pet',
    featured: false,
    itemType: 'livestock',
    sex: 'Steer',
    sizeClass: 'Micro',
    heightInches: 34,
    color: 'Silver',
    chondroStatus: 'Chondro+ (Carrier Dwarfism Gene)',
    hornStatus: 'Developing Horn Buds',
    registry: 'Pet Quality (Commercial Lineage)',
    dobOrAge: '13 Months',
    temperament: 'Extremely sweet, calm in yards, comes when called',
    vaccination: '7-in-1, Pestivirus negative, Multimin clear',
    shortDescription: 'Platinum silver micro steer. Rare fleece color with placid disposition.',
    fullDescription: 'Finley brings the luxury of the rare silver coat at a pet steer price point. Desexed, micro-sized at 34 inches, and eager to please.',
    image: '/images/finley-platinum-silver-micro-steer.webp',
    imageSourcingPrompt: 'Silver grey miniature highland steer standing near farm shed, calm posture, thick woolly coat 4:3',
  },

  // --- 1D. WEANED CALVES & BOTTLE BABIES (2 Cows) ---
  {
    id: 'mhc-61',
    slug: 'pip-silver-micro-weaned-steer-calf',
    name: 'Pip',
    price: 5400,
    category: 'paddock-companions',
    subcategory: 'weaners-calves',
    categoryLabel: 'Paddock Companions',
    subcategoryLabel: 'Weaners & Calves',
    badge: 'Weaned Calf',
    featured: true,
    itemType: 'livestock',
    sex: 'Steer Calf',
    sizeClass: 'Micro',
    heightInches: 26,
    color: 'Silver',
    chondroStatus: 'Chondro+ (Carrier Dwarfism Gene)',
    hornStatus: 'Developing Horn Buds',
    registry: 'Pet Quality (Commercial Lineage)',
    dobOrAge: '6 Months',
    temperament: 'Loves being hand-fed Lucerne, comes when called by name',
    vaccination: '7-in-1 initial + booster, drenched',
    shortDescription: 'Adorable silver micro weaner steer calf. Just 26 inches at hip.',
    fullDescription: 'Pip is fully weaned onto pasture, sweet stud muesli, and prime Lucerne hay. Super fluffy silver coat and tiny proportions make him an immediate favorite.',
    image: '/images/pip-silver-micro-weaned-steer-calf.webp',
    imageSourcingPrompt: 'Tiny silver grey baby mini highland steer calf in green clover field, big curious dark eyes, fluffy wool 4:3',
  },
  {
    id: 'mhc-62',
    slug: 'buttons-snow-white-bottle-baby-heifer-calf',
    name: 'Buttons',
    price: 7800,
    category: 'paddock-companions',
    subcategory: 'weaners-calves',
    categoryLabel: 'Paddock Companions',
    subcategoryLabel: 'Weaners & Calves',
    badge: 'Bottle Baby Heifer',
    featured: true,
    itemType: 'livestock',
    sex: 'Heifer Calf',
    sizeClass: 'Micro',
    heightInches: 25,
    color: 'Snow White',
    chondroStatus: 'Chondro+ (Carrier Dwarfism Gene)',
    hornStatus: 'Developing Horn Buds',
    registry: 'IMCBR Registered',
    dobOrAge: '4 Months',
    temperament: 'Imprinted on humans, runs to handlers for calf milk bottle',
    vaccination: '7-in-1 initial + booster, Multimin 4 clear',
    shortDescription: 'Rare pure snow-white bottle baby micro heifer. Hand-raised and deeply affectionate.',
    fullDescription: 'Buttons is an ultra-rare snow-white heifer calf raised on calf formula bottles. Bonded deeply with humans, she will follow you into the house if you let her. Eating Lucerne hay and calf pellets.',
    image: '/images/buttons-snow-white-bottle-baby-heifer-calf.webp',
    imageSourcingPrompt: 'Adorable tiny white fluffy baby highland heifer calf drinking from bottle or standing in barn straw bedding, large sweet eyes 4:3',
  },

  // =========================================================================
  // SECTION 2: 10 EXPENSIVE & PREMIUM CARE EQUIPMENT & NUTRITION ITEMS
  // =========================================================================

  {
    id: 'mhc-eq-01',
    slug: 'royal-highland-master-show-blower-dryer',
    name: 'Royal Highland Master Pro Show Blower & Dryer',
    price: 1450,
    category: 'care-equipment',
    subcategory: 'grooming-handling',
    categoryLabel: 'Care Equipment & Feed',
    subcategoryLabel: 'Grooming Blowers & Halters',
    badge: 'Essential Double-Coat Gear',
    featured: true,
    itemType: 'equipment',
    sex: 'Care Equipment',
    sizeClass: 'Universal Equipment',
    color: 'Stainless & Charcoal',
    registry: 'MHC Certified Gear',
    dimensionsOrPack: 'Dual Motor 4.0HP / 3m Reinforced Hose',
    warrantyOrShelfLife: '3-Year Commercial Stud Warranty',
    compatibility: 'Engineered specifically for thick Scottish Highland double-coats',
    shortDescription: 'High-velocity 4.0HP dual-motor dryer. Blasts debris out of dense Highland wool without heat damage.',
    fullDescription: 'The ultimate grooming tool for Scottish Highland cattle. Traditional dog dryers cannot penetrate the dense double coat of a Highland cow. This heavy-duty dual-motor blower produces 68,000 FPM airspeed to fluff the undercoat, remove dry grass seeds, and speed dry after rain or show baths. Includes 3 heavy-duty nozzles and anti-kink flex hose.',
    image: '/images/royal-highland-master-show-blower-dryer.webp',
    imageSourcingPrompt: 'Professional livestock high velocity dual motor cattle blow dryer machine with heavy duty flex hose and aluminum nozzle on clean barn floor, cattle show grooming equipment 4:3',
  },
  {
    id: 'mhc-eq-02',
    slug: 'bespoke-bridle-leather-show-halter-lead',
    name: 'Artisan Handcrafted Bridle Leather Show Halter & Brass Lead',
    price: 890,
    category: 'care-equipment',
    subcategory: 'grooming-handling',
    categoryLabel: 'Care Equipment & Feed',
    subcategoryLabel: 'Grooming Blowers & Halters',
    badge: 'Artisan Saddle Leather',
    featured: false,
    itemType: 'equipment',
    sex: 'Care Equipment',
    sizeClass: 'Universal Equipment',
    color: 'Bridle Brown & Solid Brass',
    registry: 'Australian Made',
    dimensionsOrPack: 'Custom Sized for Miniature Highland Skulls (Includes 3m Lead)',
    warrantyOrShelfLife: 'Lifetime Leather Guarantee',
    compatibility: 'Fits Micro & Miniature Highlands from 6 Months to Mature',
    shortDescription: 'Handcrafted Australian bridle leather halter with British solid brass buckles and weighted lead chain.',
    fullDescription: 'Meticulously crafted by master Australian saddlers from vegetable-tanned full-grain bridle leather. Designed specifically with wider cheekpieces and a padded crown to comfortably accommodate the broad brow and horn base of miniature Scottish Highland cattle. Includes a matching 3-meter leather lead with solid British brass chain.',
    image: '/images/bespoke-bridle-leather-show-halter-lead.webp',
    imageSourcingPrompt: 'Luxury handcrafted brown bridle leather cattle halter with polished solid brass hardware and brass lead chain laid on rustic timber wood table, artisan equestrian leather craftsmanship 4:3',
  },
  {
    id: 'mhc-eq-03',
    slug: 'highland-royal-grooming-scotch-comb-master-kit',
    name: 'Highland Master 8-Piece Rosewood Grooming & Scotch Comb Kit',
    price: 680,
    category: 'care-equipment',
    subcategory: 'grooming-handling',
    categoryLabel: 'Care Equipment & Feed',
    subcategoryLabel: 'Grooming Blowers & Halters',
    badge: 'Complete Grooming Chest',
    featured: false,
    itemType: 'equipment',
    sex: 'Care Equipment',
    sizeClass: 'Universal Equipment',
    color: 'Polished Rosewood & Stainless Steel',
    registry: 'MHC Certified Gear',
    dimensionsOrPack: '8 Professional Tools in Fitted Lockable Cedar Box',
    warrantyOrShelfLife: '5-Year Replacement Warranty',
    compatibility: 'All Highland ages — from weaners to mature bulls',
    shortDescription: 'Stainless steel shedding scotch combs, natural boar-bristle brush, detangling rakes, and cedar storage case.',
    fullDescription: 'Proper coat maintenance prevents burrs and matted underwool. This master collection includes a round-tooth stainless steel scotch comb, reversible curry comb, stiff natural boar-bristle dandy brush, soft face brush, ergonomic undercoat shedding rake, hoof rasp, and organic tea-tree coat sheen spray in a handcrafted aromatic cedar timber chest.',
    image: '/images/highland-royal-grooming-scotch-comb-master-kit.webp',
    imageSourcingPrompt: 'Professional cattle grooming tool kit in open rustic wooden chest, stainless steel scotch combs, natural bristle brushes, coat conditioning oils, high-end livestock grooming tools 4:3',
  },
  {
    id: 'mhc-eq-04',
    slug: 'automated-heavy-duty-livestock-scratch-brush-station',
    name: 'Station-Grade Spring-Loaded Paddock Cattle Scratching Brush',
    price: 2850,
    category: 'care-equipment',
    subcategory: 'paddock-shelter',
    categoryLabel: 'Care Equipment & Feed',
    subcategoryLabel: 'Troughs, Scratchers & Hay Cradles',
    badge: 'Pasture Infrastructure',
    featured: true,
    itemType: 'equipment',
    sex: 'Care Equipment',
    sizeClass: 'Universal Equipment',
    color: 'Galvanized Steel & Industrial Blue',
    registry: 'MHC Certified Gear',
    dimensionsOrPack: 'Dual Spring-Loaded Poly Rollers / Post Mount 1.8m',
    warrantyOrShelfLife: '10-Year Structural Frame Warranty',
    compatibility: 'Mounts to round timber strainers or steel fence posts',
    shortDescription: 'Heavy-duty dual rotating scratch station. Relieves fly stress and protects paddock fence posts.',
    fullDescription: 'Highland cattle instinctually seek abrasive surfaces to shed their dense winter wool. Without a dedicated brush station, cows will break timber fence rails and rubbing posts. This station-grade unit features heavy-gauge galvanized steel arms with high-density poly bristles and heavy compression springs that allow cows of all heights to safely scratch head, flanks, and rump.',
    image: '/images/automated-heavy-duty-livestock-scratch-brush-station.webp',
    imageSourcingPrompt: 'Automated livestock cattle scratching brush station installed on timber post in sunny green pasture paddock, heavy duty industrial poly bristles, farm paddock equipment 4:3',
  },
  {
    id: 'mhc-eq-05',
    slug: 'thermal-insulated-stainless-steel-water-trough',
    name: 'Thermal Double-Walled 304 Stainless Steel Automatic Water Trough (180L)',
    price: 1980,
    category: 'care-equipment',
    subcategory: 'paddock-shelter',
    categoryLabel: 'Care Equipment & Feed',
    subcategoryLabel: 'Troughs, Scratchers & Hay Cradles',
    badge: 'Clean Water System',
    featured: false,
    itemType: 'equipment',
    sex: 'Care Equipment',
    sizeClass: 'Universal Equipment',
    color: 'Food-Grade 304 Stainless Steel',
    registry: 'Australian Made',
    dimensionsOrPack: '180 Litre Capacity / 1200mm L x 600mm W x 450mm H',
    warrantyOrShelfLife: '15-Year Rust-Through Guarantee',
    compatibility: 'Standard 1/2" or 3/4" Rural Water Line / Gravity or Pressure',
    shortDescription: 'Double-walled insulated stainless drinking trough with brass rapid-fill float. Stays cool in 40°C heat.',
    fullDescription: 'Highland cattle drink up to 40 litres of water daily and refuse warm, stagnant, or algae-ridden water. This commercial 304 food-grade stainless steel trough features polyurethane thermal insulation between double walls, keeping drinking water refreshingly cool even during intense Australian summer heat. Includes an enclosed brass float valve protected from curious horns.',
    image: '/images/thermal-insulated-stainless-steel-water-trough.webp',
    imageSourcingPrompt: 'Heavy duty 304 stainless steel automatic livestock drinking water trough with clean bubbling water in lush green pasture paddock, professional cattle farm infrastructure 4:3',
  },
  {
    id: 'mhc-eq-06',
    slug: 'anti-waste-slow-feeder-round-bale-cradle',
    name: 'Galvanized Anti-Waste Slow-Feeder Round Bale Cradle with Weather Canopy',
    price: 2250,
    category: 'care-equipment',
    subcategory: 'paddock-shelter',
    categoryLabel: 'Care Equipment & Feed',
    subcategoryLabel: 'Troughs, Scratchers & Hay Cradles',
    badge: 'Hay Saver Innovation',
    featured: false,
    itemType: 'equipment',
    sex: 'Care Equipment',
    sizeClass: 'Universal Equipment',
    color: 'Hot-Dip Galvanized & Poly Roof',
    registry: 'Australian Made',
    dimensionsOrPack: 'Holds 4x4 or 5x4 Round Bales / Built-in Rain Canopy',
    warrantyOrShelfLife: '10-Year Hot-Dip Galvanized Warranty',
    compatibility: 'Engineered horn-safe spacing for miniature cattle',
    shortDescription: 'Cradle feeder with 2-inch slow-feed steel mesh and rain roof. Reduces hay wastage by up to 45%.',
    fullDescription: 'Highland cattle are notorious for pulling expensive hay onto the dirt and trampling it. This heavy-duty round-bale cradle elevates the bale 30cm off damp ground and utilizes a contoured slow-feed grid that prevents cattle gorging while eliminating waste. The UV-treated polyethylene roof keeps premium hay dry and mold-free during rain.',
    image: '/images/anti-waste-slow-feeder-round-bale-cradle.webp',
    imageSourcingPrompt: 'Covered round bale hay feeder cradle with steel slow feed grid in pasture paddock, miniature cattle farm equipment, clean green lawn background 4:3',
  },
  {
    id: 'mhc-eq-07',
    slug: 'highland-all-weather-ripstop-paddock-blanket-rug',
    name: 'Highland WeatherMaster 1200D Ripstop Waterproof Paddock Blanket & Rug',
    price: 540,
    category: 'care-equipment',
    subcategory: 'grooming-handling',
    categoryLabel: 'Care Equipment & Feed',
    subcategoryLabel: 'Grooming Blowers & Halters',
    badge: 'Show & Weather Protection',
    featured: false,
    itemType: 'equipment',
    sex: 'Care Equipment',
    sizeClass: 'Universal Equipment',
    color: 'Forest Green with Tartan Trim',
    registry: 'MHC Certified Gear',
    dimensionsOrPack: 'Custom Cut for Deep-Girth Miniature Highland Body Frame',
    warrantyOrShelfLife: '2-Year Hardware & Stitching Warranty',
    compatibility: 'Sizes 3\'6" to 4\'9" (Micro to Miniature cattle)',
    shortDescription: '1200D waterproof breathable turnout rug with sheepskin wither fleece and twin surcingles.',
    fullDescription: 'Ideal for sick, recovering, or show cattle requiring pristine coat preservation. Fabricated with heavy-duty 1200 Denier ripstop waterproof fabric, 200g thermal polyfill, natural sheepskin wither protector, and deep shoulder gussets contoured to allow natural grazing posture without rubbing off mane hair.',
    image: '/images/highland-all-weather-ripstop-paddock-blanket-rug.webp',
    imageSourcingPrompt: 'Heavy duty dark forest green waterproof canvas cattle blanket rug with sheepskin wither fleece and brass buckles folded over rustic timber rail fence 4:3',
  },
  {
    id: 'mhc-eq-08',
    slug: 'certified-prime-lucerne-teff-hay-pallet',
    name: 'Certified Export-Grade Prime Lucerne & Soft Teff Hay Pallet (24 Compressed Bales)',
    price: 1250,
    category: 'care-equipment',
    subcategory: 'feed-nutrition',
    categoryLabel: 'Care Equipment & Feed',
    subcategoryLabel: 'Lucerne Hay & Stud Nutrition',
    badge: 'Export Grade Forage',
    featured: true,
    itemType: 'feed',
    sex: 'Feed & Nutrition',
    sizeClass: 'Feed Supply',
    color: 'Rich Green & Golden Amber',
    registry: 'Australian Certified Organic',
    dimensionsOrPack: 'Pallet of 24 High-Density Bales (Approx 600kg Total)',
    warrantyOrShelfLife: '12-Month Cool Storage Guarantee',
    compatibility: 'Safe daily forage for all mini highland calves and cows',
    shortDescription: 'Chemical-free weed-tested green Lucerne and low-sugar leafy Teff hay. Essential rumen nutrition.',
    fullDescription: 'Grown in the fertile Lockyer Valley and Darling Downs under precision irrigation. This half-tonne pallet contains 12 bales of leafy high-protein Prime Lucerne (Alfalfa) and 12 bales of low-sugar, high-digestibility Teff grass hay. Tested free of invasive weed seeds, endophytes, and mold. Palletized and shrink-wrapped for clean delivery direct to your property.',
    image: '/images/certified-prime-lucerne-teff-hay-pallet.webp',
    imageSourcingPrompt: 'Stack of fragrant premium green Lucerne alfalfa and soft leafy teff hay bales neatly wrapped on wooden pallet in clean barn, golden farm sunlight 4:3',
  },
  {
    id: 'mhc-eq-09',
    slug: 'highland-stud-royal-conditioning-sweet-muesli',
    name: 'Highland Stud Royal Conditioning Sweet Muesli & Omega-3 Coat Blend (10x 20kg)',
    price: 920,
    category: 'care-equipment',
    subcategory: 'feed-nutrition',
    categoryLabel: 'Care Equipment & Feed',
    subcategoryLabel: 'Lucerne Hay & Stud Nutrition',
    badge: 'Veterinary Formulated',
    featured: false,
    itemType: 'feed',
    sex: 'Feed & Nutrition',
    sizeClass: 'Feed Supply',
    color: 'Golden Grains with Molasses & Flax',
    registry: 'Australian Made',
    dimensionsOrPack: '10x 20kg Heavy-Duty Foil-Lined Woven Sacks (200kg Total)',
    warrantyOrShelfLife: '9-Month Freshness Seal',
    compatibility: 'Daily training treat and show conditioning ration',
    shortDescription: 'Micronized steam-flaked barley, lupins, cold-pressed flaxseed oil, and chelated minerals for show-ring coat shine.',
    fullDescription: 'Formulated exclusively by Australian livestock nutritionists to produce the iconic glossy double coat of Highland cattle. Contains micronized steam-flaked grains for maximum starch digestibility, cold-pressed flaxseed oil (rich in Omega 3 & 6), organic kelp meal, chelated zinc, and biotin to promote dense horn growth and thick, shiny wool.',
    image: '/images/highland-stud-royal-conditioning-sweet-muesli.webp',
    imageSourcingPrompt: 'Close up of luxury textured sweet feed muesli for cattle with steam flaked barley, molasses, lupins, sunflower seeds and minerals in rustic wooden scoop 4:3',
  },
  {
    id: 'mhc-eq-10',
    slug: 'organic-atlantic-sea-kelp-mineral-lick-tubs',
    name: 'Organic Atlantic Sea-Kelp & Chelated Trace Mineral Lick Tubs (4x 40kg Tubs)',
    price: 780,
    category: 'care-equipment',
    subcategory: 'feed-nutrition',
    categoryLabel: 'Care Equipment & Feed',
    subcategoryLabel: 'Lucerne Hay & Stud Nutrition',
    badge: 'Bio-Available Minerals',
    featured: false,
    itemType: 'feed',
    sex: 'Feed & Nutrition',
    sizeClass: 'Feed Supply',
    color: 'Rich Molasses Brown in Weatherproof Tub',
    registry: 'Australian Certified Organic',
    dimensionsOrPack: '4x 40kg Weatherproof Heavy Poly Tubs (160kg Total)',
    warrantyOrShelfLife: '24-Month Weatherproof Paddock Life',
    compatibility: 'Continuous free-choice paddock access for cattle of all ages',
    shortDescription: 'Fortified molasses, kelp, magnesium, copper, and selenium lick tubs. Weatherproof formulation.',
    fullDescription: 'Australian soils are notoriously deficient in selenium, copper, and cobalt—critical trace elements required for Highland coat pigmentation, strong immune response, and hoof hardness. These low-intake molasses lick tubs withstand rain without dissolving, allowing cattle to self-regulate their micronutrient intake naturally year-round.',
    image: '/images/organic-atlantic-sea-kelp-mineral-lick-tubs.webp',
    imageSourcingPrompt: 'Heavy duty livestock molasses and organic seaweed mineral lick block tub placed in lush green grass paddock pasture, natural cattle supplement block 4:3',
  },
];

export const ALL_PRODUCTS = PRODUCTS;

export const SHOP = {
  minOrder: 0,
  freeShippingThreshold: 2000,
  shippingFee: 0,
  cryptoDiscount: 10,
  paymentMethods: ['crypto-BTC', 'crypto-USDT', 'bank-transfer'],
};

export interface FaqItem {
  q: string;
  a: string;
}

export const FAQS: FaqItem[] = [
  {
    q: 'How does live cattle reservation and delivery work in Australia?',
    a: 'You select the animal and submit an enquiry or holding deposit. We verify your state PIC (Property Identification Code), arrange a pre-delivery veterinary health check, and coordinate door-to-paddock transport via accredited livestock carriers across QLD, NSW, VIC, SA, and WA.',
  },
  {
    q: 'Can I order care equipment, blowers, and feed alongside my cow?',
    a: 'Yes! All 10 premium care equipment and nutrition products (such as high-velocity blowers, handcrafted leather halters, slow-feed hay cradles, and export Lucerne hay pallets) can be bundled directly with your livestock order and dispatched on the same biosecure transport or freighted directly to your property.',
  },
  {
    q: 'What is a PIC and do I need one before buying a miniature cow?',
    a: 'Yes. In Australia, any property keeping livestock (even a single pet cow) requires a Property Identification Code (PIC) from your state Department of Primary Industries or Local Land Services. It is free or low-cost and takes only a few minutes to register online. Note: PIC is NOT required if you are only ordering equipment or feed.',
  },
  {
    q: 'What is the difference between Micro and Miniature Highland cattle?',
    a: 'Miniature Highlands mature between 36 and 42 inches (91–106 cm) at the hip at 3 years old. Micro Highlands mature under 36 inches (under 91 cm). Both have the iconic long double coat, wide heads, and calm disposition.',
  },
  {
    q: 'What does Chondro-tested (Negative vs Carrier) mean?',
    a: 'Chondrodysplasia is a genetic dwarfism gene present in some miniature cattle. A non-carrier (negative) animal achieves compact size through generational selection without the dwarf gene. A chondro+ carrier carries one copy of the gene, resulting in shorter legs. We test and disclose the status of every single animal.',
  },
  {
    q: 'How much acreage do I need for a miniature Highland cow?',
    a: 'As a rule of thumb, we recommend at least 1 to 2 acres of clean, securely fenced pasture per animal, along with a companion animal (another cow, horse, or sheep), adequate fresh water, shade, and supplemental hay in dry seasons.',
  },
  {
    q: 'Are your cattle halter trained and vaccinated?',
    a: 'All our cattle undergo halter training, regular handling, and grooming. Every animal is vaccinated with 7-in-1, tested negative for Pestivirus (BVDV), drenched, and transferred with an NLIS RFID ear tag.',
  },
  {
    q: 'What payment methods do you accept?',
    a: 'We accept secure Direct Bank Transfer (EFT/Osko) within Australia, as well as cryptocurrency (Bitcoin BTC and USDT) which automatically receives an exclusive 10% discount on the total livestock or equipment purchase price.',
  },
];

export const FAQ = FAQS.map((f) => ({ question: f.q, answer: f.a }));

export interface AnimalOrderSpecs {
  earTag: string;
  nlisRfid: string;
  estimatedWeightKg: number;
  projectedMatureWeightKg: number;
  heightCm: number;
  sirePedigree: string;
  damPedigree: string;
  healthCertification: string;
  vaccinesCurrent: string;
  parasiteProtocol: string;
  shippingEligibility: string;
  shippingTimeframe: string;
  biosecurityStatus: string;
  buyerPicRequirement: string;
}

export function getAnimalOrderSpecs(animal: AnimalProduct): AnimalOrderSpecs {
  const numericId = animal.id.replace(/\D/g, '') || '01';

  // Handle equipment and feed items gracefully
  if (animal.itemType === 'equipment' || animal.itemType === 'feed' || animal.category === 'care-equipment') {
    const isFeed = animal.itemType === 'feed' || animal.subcategory === 'feed-nutrition';
    return {
      earTag: `MHC-GEAR-${numericId}`,
      nlisRfid: 'N/A (Livestock Equipment & Nutrition Item)',
      estimatedWeightKg: isFeed ? 200 : 45,
      projectedMatureWeightKg: isFeed ? 200 : 45,
      heightCm: 0,
      sirePedigree: 'MHC Stud Verified Equipment Specification',
      damPedigree: animal.registry || 'Australian Made & Quality Inspected',
      healthCertification: 'Australian Quality Standards & Biosecurity Clean Certified',
      vaccinesCurrent: 'N/A — Manufactured Equipment & Sealed Feed Supply',
      parasiteProtocol: 'Clean Storage & Sealed Pest-Free Pallet Packaging',
      shippingEligibility: '100% Eligible for Direct Door Delivery or Freight with Livestock',
      shippingTimeframe: '3–7 Business Days Direct to Your Property Address',
      biosecurityStatus: 'Brand New / Sealed Biosecure Stock Ready for Farm Dispatch',
      buyerPicRequirement: 'Not Required for Equipment & Feed Purchases (Optional PIC on file)',
    };
  }

  // Livestock handling
  const heightCm = Math.round((animal.heightInches || 36) * 2.54);

  let estimatedWeightKg = 180;
  let projectedMatureWeightKg = 280;

  if (animal.subcategory === 'cows-in-calf-pairs') {
    estimatedWeightKg = animal.sex === 'Breeding Pair' ? 420 : 320;
    projectedMatureWeightKg = animal.sex === 'Breeding Pair' ? 650 : 360;
  } else if (animal.subcategory === 'steers') {
    estimatedWeightKg = animal.sizeClass === 'Micro' ? 140 : 200;
    projectedMatureWeightKg = animal.sizeClass === 'Micro' ? 220 : 300;
  } else if (animal.subcategory === 'weaners-calves') {
    estimatedWeightKg = animal.id === 'mhc-62' ? 55 : 85;
    projectedMatureWeightKg = animal.sizeClass === 'Micro' ? 210 : 260;
  } else {
    // heifers
    estimatedWeightKg = animal.sizeClass === 'Micro' ? 130 : 180;
    projectedMatureWeightKg = animal.sizeClass === 'Micro' ? 210 : 270;
  }

  // Scottish foundation bloodlines
  const sireNames = [
    'Balgownie Finlay (AHCS #8210 - Scottish Import Sire)',
    'Strathbogie Glen (AHCS #7954 - Champion Silver Sire)',
    'Lochiel Hamish (AHCS #8391 - Foundation Micro Bull)',
    'Glenrowan Jock (IMCBR #4012 - Polled Dun Genetics)',
    'Inverness Royal Laddie (AHCS #8045 - Red Heritage Sire)',
  ];

  const damNames = [
    'Lochiel Bonnie (AHCS #7944 - Scottish Foundation Dam)',
    'Braemar Heather Lass (AHCS #7712 - Elite Micro Dam)',
    'Kintyre Sweet Rose (AHCS #8150 - White Dun Dam)',
    'Highland Glens Fiona (AHCS #7833 - Champion Heifer Dam)',
    'Tweed River Morag (AHCS #8201 - Docile Paddock Matron)',
  ];

  const hash = parseInt(numericId, 10) || 1;
  const sirePedigree = sireNames[hash % sireNames.length];
  const damPedigree = damNames[(hash + 2) % damNames.length];

  return {
    earTag: `MHC-QLD-${numericId}`,
    nlisRfid: `982 000 364 892 1${numericId}`,
    estimatedWeightKg,
    projectedMatureWeightKg,
    heightCm,
    sirePedigree,
    damPedigree,
    healthCertification: 'National Vendor Declaration (NVD) & Pre-Transport Veterinary Certificate',
    vaccinesCurrent: 'Ultravac 7-in-1 (Clostridial & Leptospirosis) + 5-in-1 Booster + Pestivirus (BVDV) Clear',
    parasiteProtocol: 'Cydectin Platinum Pour-on + Multimin 4 Selenium Copper injection complete',
    shippingEligibility: '100% Eligible for Direct Door-to-Paddock Transport Nationwide',
    shippingTimeframe: '5–10 Business Days Direct to Your Property Address',
    biosecurityStatus: 'Closed-Herd Biosecurity (Zero Public On-Farm Visits to Maintain Pathogen-Free Status)',
    buyerPicRequirement: 'State Property Identification Code (MHC desk provides free assistance if needed)',
  };
}

export const FAQ_ITEMS = [
  {
    question: 'What is the maximum height of a true Miniature vs Micro Highland cow?',
    answer:
      'In Australia, Miniature Highland cattle must measure 42 inches (106 cm) or less at the hip at 3 years of age. Micro Highland cattle measure 36 inches (91 cm) or less at maturity. MHC strictly NEVER sells commercial or standard-sized cattle (which measure 48–56 inches and weigh up to 900kg).',
  },
  {
    question: 'How much acreage do I need to keep miniature Highland cows?',
    answer:
      'As a general rule, a pair of miniature Highland cattle requires 1 to 2 acres of quality grass pasture with seasonal rotational grazing. Cattle are naturally herd animals, so we strictly recommend keeping at least two animals together or pairing them with an existing friendly livestock companion.',
  },
  {
    question: 'What is a Property Identification Code (PIC) and is it legally required?',
    answer:
      'Yes, under Australian biosecurity law, anyone keeping cattle—even a single pet miniature steer on a lifestyle acreage—must hold a valid Property Identification Code (PIC). A PIC is issued by your state agricultural department (e.g., Biosecurity Queensland, NSW Local Land Services, Agriculture Victoria) and takes only minutes to register online. MHC assists every buyer with the registration process.',
  },
  {
    question: 'How does National Livestock Identification System (NLIS) transfer work?',
    answer:
      'Every miniature calf bred at MHC PTY LTD is fitted with an official National Livestock Identification System (NLIS) electronic RFID ear tag prior to dispatch. When your animal is loaded for transit, our office logs onto the national database and completes the electronic livestock transfer directly to your property PIC at no extra charge.',
  },
  {
    question: 'What is your Chondrodysplasia (Dwarfism) breeding policy?',
    answer:
      'We DNA test 100% of our breeding stock for the Chondrodysplasia gene. While carrier animals (Chondro+) are healthy and boast desired short-leg conformation, mating two carriers together carries a 25% risk of lethal bulldog calf syndrome. MHC strictly pairs carriers only with non-carriers (Chondro-Free), guaranteeing 100% healthy, viable calves with official DNA certificates.',
  },
  {
    question: 'Why do you operate under a Closed-Gate Biosecurity policy?',
    answer:
      'To guarantee the health of our herd and protect young calves from infectious diseases (such as Bovine Viral Diarrhea/Pestivirus, Tick Fever, and Leptospirosis), our Roma, QLD stud operates a strict closed-gate biosecurity perimeter. We do not host public drive-in tours. Instead, all cattle are dispatched via accredited livestock transport with full veterinary health clearances directly to your property gate.',
  },
  {
    question: 'What fencing and shelter do miniature Highland cattle need?',
    answer:
      'Standard 4-to-5 strand post-and-wire or ringlock rural fencing (approx 1.2m high) is ideal. Because Highland cattle have thick double coats, they need access to shade (trees or a simple three-sided run-in shed), fresh drinking water, and dry ground. Electric outrigger wires are recommended to prevent cattle from scratching against and loosening fence wires.',
  },
  {
    question: 'What payment methods do you accept and how does delivery work?',
    answer:
      'We accept secure direct Australian bank transfers (EFT/Osko) and cryptocurrency (Bitcoin BTC and Tether USDT with a 10% instant discount). Live cattle orders require a 20% holding deposit with the balance due prior to livestock carrier dispatch. Door-to-paddock livestock transport is arranged nationwide across QLD, NSW, VIC, SA, and WA.',
  },
];

export const BLOG_POSTS = [
  {
    slug: 'how-much-do-mini-highland-cows-cost-australia',
    title: 'How Much Do Miniature Highland Cows Cost in Australia? (2025/2026 Price Guide)',
    excerpt:
      'A realistic, transparent breakdown of miniature and micro Highland cattle pricing across Australia, covering pet steers, breeding foundation heifers, and in-calf pairs.',
    date: 'February 2025',
    datePublished: '2025-02-01',
    readTime: '6 min read',
    image: '/images/isla-silver-micro-heifer.webp',
  },
  {
    slug: 'micro-vs-mini-highland-explained',
    title: 'Micro vs Miniature Highland Cattle: Australian Standards, Heights & Genetics',
    excerpt:
      'Everything lifestyle acreage owners need to know about official hip height standards, adult weight ranges, and responsible Chondrodysplasia genetics.',
    date: 'January 2025',
    datePublished: '2025-01-01',
    readTime: '8 min read',
    image: '/images/thistle-snow-white-micro-heifer.webp',
  },
  {
    slug: 'pic-and-nlis-explained-australia',
    title: 'Australian Livestock Legal Guide: Property Identification Codes (PIC) & NLIS Transfers',
    excerpt:
      'A complete step-by-step guide on how to register your lifestyle acreage for a PIC, understand NLIS electronic RFID ear tags, and comply with state biosecurity laws.',
    date: 'December 2024',
    datePublished: '2024-12-01',
    readTime: '7 min read',
    image: '/images/bramble-jet-black-micro-heifer.webp',
  },
  {
    slug: 'why-miniature-highland-steers-make-the-best-paddock-companions',
    title: 'Why Halter-Trained Miniature Highland Steers Make the Best Lifestyle Acreage Companions',
    excerpt:
      'Docile, loving, and easy to manage—discover why desexed miniature steers are the #1 choice for Australian families, hobby farmers, and lifestyle acreage owners seeking gentle paddock pets.',
    date: 'March 2025',
    datePublished: '2025-03-04',
    readTime: '6 min read',
    image: '/images/angus-tiger-brindle-micro-pet-steer.webp',
  },
  {
    slug: 'miniature-highland-grooming-blowers-and-coat-care-guide',
    title: 'Miniature Highland Cow Grooming Masterclass: Blowers, Scotch Combs & Seasonal Shedding',
    excerpt:
      'Master the Scottish double-coat: high-velocity livestock blowers, scotch combs, fly defense, and winter conditioning for healthy, radiant paddock and show cattle.',
    date: 'March 2025',
    datePublished: '2025-03-12',
    readTime: '7 min read',
    image: '/images/royal-highland-master-show-blower-dryer.webp',
  },
  {
    slug: 'starting-a-miniature-highland-fold-foundation-pairs',
    title: 'Starting Your Own Miniature Highland Fold: Selecting Foundation Pairs & Genetics',
    excerpt:
      'A breeder’s guide to bloodlines, pedigree registration, pasture rotation, and managing your first calving season on Australian acreage with matched foundation pairs.',
    date: 'March 2025',
    datePublished: '2025-03-20',
    readTime: '9 min read',
    image: '/images/rory-and-fern-silver-foundation-breeding-pair.webp',
  },
];

// Alias for livestock & products catalog
export const ANIMALS = PRODUCTS;
